language: python
python:
  - "3.7"
install:
  - make setup-all
  - pipenv install --dev codecov
script:
  - pipenv run flake8 py_proxy testsuite
  - pipenv run coverage run setup.py test

after_success:
  - pipenv run codecov