language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - python setup.py flake8
  - coverage run setup.py test

after_success:
  - codecov